import { createFileRoute } from "@tanstack/react-router";

import { AppShell } from "@/components/netdoc/AppShell";
import { FloorPlanViewer } from "@/components/netdoc/FloorPlanViewer";
import { HeatmapLegend } from "@/components/netdoc/HeatmapLegend";
import { MetricGrid } from "@/components/netdoc/MetricGrid";
import { SignalChart } from "@/components/netdoc/SignalChart";
import { SurveyControls } from "@/components/netdoc/SurveyControls";
import { Button } from "@/components/ui/button";
import { useSurvey } from "@/lib/survey/store";

export const Route = createFileRoute("/survey")({
  head: () => ({
    meta: [
      { title: "Live Wi-Fi Survey — NetDoc WiFi Survey" },
      { name: "description", content: "Walk a floor plan and record live RSSI, SNR and link-rate measurements from a local Wi-Fi agent." },
      { property: "og:title", content: "Live Wi-Fi Survey — NetDoc" },
      { property: "og:description", content: "Record live RSSI, SNR and throughput measurements onto a calibrated floor plan." },
    ],
  }),
  component: SurveyPage,
});

function SurveyPage() {
  const { samples, chartsPaused, setChartsPaused, layer, thresholds, positionSource, position, mode } = useSurvey();
  const chartSamples = chartsPaused ? samples.slice(0, Math.max(0, samples.length - 1)) : samples;

  return (
    <AppShell title="Live Survey">
      <div className="space-y-3">
        <MetricGrid />
        <SurveyControls />
        <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_330px]">
          <FloorPlanViewer className="min-h-[540px]" />
          <div className="space-y-3">
            <div className="panel-surface p-3 text-xs">
              <div className="label-caps mb-1">Positioning</div>
              <div className="mono-num text-sm text-foreground">
                {position
                  ? positionSource === "manual"
                    ? "Position: Floor Plan Manual"
                    : positionSource === "agent"
                      ? "Position: Local Agent"
                      : "Position: Demo Walk"
                  : "Position: Not available"}
              </div>
              <p className="mt-1 text-muted-foreground">
                {mode === "live"
                  ? "Click your location on the plan as you walk. GPS is never mapped to indoor coordinates automatically."
                  : "Simulated walk positions are generated by the demo engine."}
              </p>
            </div>
            <HeatmapLegend layer={layer} thresholds={thresholds} />
            <div className="flex justify-end">
              <Button size="sm" variant="outline" className="h-8 text-xs" onClick={() => setChartsPaused(!chartsPaused)}>
                {chartsPaused ? "Resume charts" : "Pause charts"}
              </Button>
            </div>
            <SignalChart metric="rssi" samples={chartSamples} height={120} />
            <SignalChart metric="snr" samples={chartSamples} height={120} />
          </div>
        </div>
      </div>
    </AppShell>
  );
}
