/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessPointsRouteImport } from './routes/access-points'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as NetworksRouteImport } from './routes/networks'
import { Route as SurveyRouteImport } from './routes/survey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessPointsRoute = AccessPointsRouteImport.update({
  id: '/access-points',
  path: '/access-points',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworksRoute = NetworksRouteImport.update({
  id: '/networks',
  path: '/networks',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-points': typeof AccessPointsRoute
  '/heatmap': typeof HeatmapRoute
  '/networks': typeof NetworksRoute
  '/survey': typeof SurveyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-points': typeof AccessPointsRoute
  '/heatmap': typeof HeatmapRoute
  '/networks': typeof NetworksRoute
  '/survey': typeof SurveyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-points': typeof AccessPointsRoute
  '/heatmap': typeof HeatmapRoute
  '/networks': typeof NetworksRoute
  '/survey': typeof SurveyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/access-points' | '/heatmap' | '/networks' | '/survey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/access-points' | '/heatmap' | '/networks' | '/survey'
  id: '__root__' | '/' | '/access-points' | '/heatmap' | '/networks' | '/survey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessPointsRoute: typeof AccessPointsRoute
  HeatmapRoute: typeof HeatmapRoute
  NetworksRoute: typeof NetworksRoute
  SurveyRoute: typeof SurveyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-points': {
      id: '/access-points'
      path: '/access-points'
      fullPath: '/access-points'
      preLoaderRoute: typeof AccessPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/networks': {
      id: '/networks'
      path: '/networks'
      fullPath: '/networks'
      preLoaderRoute: typeof NetworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessPointsRoute: AccessPointsRoute,
  HeatmapRoute: HeatmapRoute,
  NetworksRoute: NetworksRoute,
  SurveyRoute: SurveyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
